# GitHub Pagesに公開
name: GitHub Pages

on:
  # trigger
  push:
    branches: [master]

jobs:
  publish-gh-pages:
    runs-on: ubuntu-latest

    steps:
      - name: Push gh-pages branch
        uses: peaceiris/actions-gh-pages@v3        